version: '3.2'
services:

  auth-app-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: auth-app-backend
    networks:
      - default
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend/app:/app:rw
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    entrypoint: /entrypoint.sh
    env_file:
      - ./backend/environments/dev.env
    command: python manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
  
  auth-app-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: auth-app-frontend
    networks:
      - default
    working_dir: /app
    ports:
      - "4200:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frontend/app:/app:rw

      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      - staticfiles:/staticfiles:ro
      - mediafiles:/mediafiles:ro
    depends_on:
      auth-app-backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  staticfiles:
  mediafiles:

networks:
  default:
    name: auth-app-dev
